version: '2'

networks:
  procrustus_network:
    external:
      name: nginxproxynetwork

services:
  procrustes-app:
    build:
      context: ./
      dockerfile: Dockerfile.client
    container_name: procrustes_app
    environment:
      - VIRTUAL_HOST=ga.sd.di.huc.knaw.nl
    volumes:
      - /home/robz/:/home
    ports:
      - 8666:80
    networks:
      - procrustus_network
